import imgLaptop1 from "../../webp/product01.webp";
import imgLaptop2 from "../../webp/product03.webp";
import imgLaptop3 from "../../webp/product06.webp";
import imgLaptop4 from "../../webp/product08.webp";
import imgPhone from "../../webp/product07.webp";
import imgIpod from "../../webp/product04.webp";
import imgHeadphone1 from "../../webp/product02.webp";
import imgHeadphone2 from "../../webp/product05.webp";
import imgCamera from "../../webp/product09.webp";

export const DataOne = [
  {
    id: 1,
    img: imgLaptop1,
    title: "Laptop hp",
    des: "8 Ram ,256 ssd",
    price: 1000,
    stars: 4,
  },
  {
    id: 2,
    img: imgHeadphone1,
    title: "HeadPhone",
    des: "hight edtions 2025 ",
    price: 120,
    stars: 4.5,
  },
  {
    id: 3,
    img: imgIpod,
    title: "Ipad",
    des: "8 Ram ,256 , ios 18",
    price: 1199,
    stars: 3.8,
  },
  {
    id: 4,
    img: imgCamera,
    title: "Camera",
    des: "type cannon ,200 mpx ",
    price: 699,
    stars: 4.7,
  },
];

export const DataTwo = [
  {
    id: 1,
    img: imgLaptop2,
    title: "Laptop hp",
    des: "8 Ram ,256 ssd",
    price: 1000,
    stars: 4,
  },
  {
    id: 2,
    img: imgHeadphone2,
    title: "HeadPhone",
    des: "hight edtions 2025 ",
    price: 120,
    stars: 4.5,
  },
  {
    id: 3,
    img: imgIpod,
    title: "Ipad",
    des: "8 Ram ,256 , ios 18",
    price: 1199,
    stars: 3.8,
  },
  {
    id: 4,
    img: imgPhone,
    title: "Phone",
    des: "6 Ram ,128 ssd",
    price: 700,
    stars: 4,
  },
  {
    id: 5,
    img: imgHeadphone1,
    title: "HeadPhone",
    des: "hight edtions 2025 ",
    price: 250,
    stars: 4.5,
  },
  {
    id: 6,
    img: imgLaptop4,
    title: "Laptop",
    des: "8 Ram , 256 ssd",
    price: 1799,
    stars: 3.8,
  },
  {
    id: 7,
    img: imgIpod,
    title: "Ipad",
    des: "8 Ram ,256 , ios 18",
    price: 1199,
    stars: 3.8,
  },
  {
    id: 8,
    img: imgLaptop3,
    title: "Laptop",
    des: "8 Ram , 256 ssd",
    price: 1799,
    stars: 3.8,
  },
  {
    id: 9,
    img: imgCamera,
    title: "Camera",
    des: "type cannon ,200 mpx ",
    price: 699,
    stars: 4.7,
  },
  {
    id: 10,
    img: imgLaptop1,
    title: "Laptop hp",
    des: "8 Ram ,256 ssd",
    price: 1000,
    stars: 4,
  },
  {
    id: 11,
    img: imgHeadphone1,
    title: "HeadPhone",
    des: "hight edtions 2025 ",
    price: 250,
    stars: 4.5,
  },
  {
    id: 12,
    img: imgHeadphone2,
    title: "HeadPhone",
    des: "hight edtions 2025 ",
    price: 120,
    stars: 4.5,
  },
  {
    id: 13,
    img: imgLaptop2,
    title: "Laptop",
    des: "8 Ram , 256 ssd",
    price: 1799,
    stars: 3.8,
  },
  {
    id: 14,
    img: imgCamera,
    title: "Camera",
    des: "type cannon ,200 mpx ",
    price: 699,
    stars: 4.7,
  },
  {
    id: 15,
    img: imgLaptop4,
    title: "Laptop",
    des: "8 Ram , 256 ssd",
    price: 1799,
    stars: 3.8,
  },
];

export const DataThree = [
  {
    id: 1,
    img: imgLaptop2,
    title: "Laptop hp",
    des: "8 Ram ,256 ssd",
    price: 1000,
    discount: true,
    discountPrice: 950,
    stars: 4,
  },
  {
    id: 2,
    img: imgHeadphone2,
    title: "HeadPhone",
    des: "hight edtions 2025 ",
    price: 120,
    discount: true,
    discountPrice: 100,
    stars: 4.5,
  },
  {
    id: 3,
    img: imgIpod,
    title: "Ipad",
    des: "8 Ram ,256 , ios 18",
    price: 1199,
    discount: true,
    discountPrice: 1099,
    stars: 3.8,
  },
  {
    id: 4,
    img: imgPhone,
    title: "Phone",
    des: "6 Ram ,128 ssd",
    price: 700,
    discount: true,
    discountPrice: 610,
    stars: 4,
  },
  {
    id: 5,
    img: imgHeadphone1,
    title: "HeadPhone",
    des: "hight edtions 2025 ",
    price: 250,
    discount: false,
    discountPrice: 90,
    stars: 4.5,
  },
  {
    id: 6,
    img: imgLaptop4,
    title: "Laptop",
    des: "8 Ram , 256 ssd",
    price: 1799,
    discount: false,
    discountPrice: 1600,
    stars: 3.8,
  },
  {
    id: 7,
    img: imgIpod,
    title: "Ipad",
    des: "8 Ram ,256 , ios 18",
    price: 1199,
    discount: true,
    discountPrice: 1099,
    stars: 3.8,
  },
  {
    id: 8,
    img: imgLaptop3,
    title: "Laptop",
    des: "8 Ram , 256 ssd",
    price: 1799,
    discount: true,
    discountPrice: 1600,
    stars: 3.8,
  },
  {
    id: 9,
    img: imgCamera,
    title: "Camera",
    des: "type cannon ,200 mpx ",
    price: 699,
    discount: true,
    discountPrice: 571,
    stars: 4.7,
  },
  {
    id: 10,
    img: imgLaptop1,
    title: "Laptop hp",
    des: "8 Ram ,256 ssd",
    price: 1000,
    discount: true,
    discountPrice: 910,
    stars: 4,
  },
  {
    id: 11,
    img: imgHeadphone1,
    title: "HeadPhone",
    des: "hight edtions 2025 ",
    price: 250,
    discount: false,
    discountPrice: 190,
    stars: 4.5,
  },
  {
    id: 12,
    img: imgHeadphone2,
    title: "HeadPhone",
    des: "hight edtions 2025 ",
    price: 120,
    discount: true,
    discountPrice: 90,
    stars: 4.5,
  },
  {
    id: 13,
    img: imgLaptop2,
    title: "Laptop",
    des: "8 Ram , 256 ssd",
    price: 1799,
    discount: true,
    discountPrice: 1600,
    stars: 3.8,
  },
  {
    id: 14,
    img: imgCamera,
    title: "Camera",
    des: "type cannon ,200 mpx ",
    price: 699,
    discount: false,
    discountPrice: 570,
    stars: 4.7,
  },
  {
    id: 15,
    img: imgLaptop4,
    title: "Laptop",
    des: "8 Ram , 256 ssd",
    price: 1799,
    discount: true,
    discountPrice: 1680,
    stars: 3.8,
  },
  {
    id: 16,
    img: imgLaptop2,
    title: "Laptop hp",
    des: "8 Ram ,256 ssd",
    price: 1000,
    discount: false,
    discountPrice: 910,
    stars: 4,
  },
  {
    id: 17,
    img: imgHeadphone2,
    title: "HeadPhone",
    des: "hight edtions 2025 ",
    price: 120,
    discount: false,
    discountPrice: 90,
    stars: 4.5,
  },
  {
    id: 18,
    img: imgIpod,
    title: "Ipad",
    des: "8 Ram ,256 , ios 18",
    price: 1199,
    discount: true,
    discountPrice: 1081,
    stars: 3.8,
  },
  {
    id: 19,
    img: imgPhone,
    title: "Phone",
    des: "6 Ram ,128 ssd",
    price: 700,
    discount: true,
    discountPrice: 590,
    stars: 4,
  },
  {
    id: 20,
    img: imgHeadphone1,
    title: "HeadPhone",
    des: "hight edtions 2025 ",
    price: 250,
    discount: true,
    discountPrice: 190,
    stars: 4.5,
  },
  {
    id: 21,
    img: imgLaptop4,
    title: "Laptop",
    des: "8 Ram , 256 ssd",
    price: 1799,
    discount: true,
    discountPrice: 1790,
    stars: 3.8,
  },
  {
    id: 22,
    img: imgIpod,
    title: "Ipad",
    des: "8 Ram ,256 , ios 18",
    price: 1199,
    discount: true,
    discountPrice: 1099,
    stars: 3.8,
  },
  {
    id: 23,
    img: imgLaptop3,
    title: "Laptop",
    des: "8 Ram , 256 ssd",
    price: 1799,
    discount: true,
    discountPrice: 1570,
    stars: 3.8,
  },
  {
    id: 24,
    img: imgCamera,
    title: "Camera",
    des: "type cannon ,200 mpx ",
    price: 699,
    discount: true,
    discountPrice: 590,
    stars: 4.7,
  },
  {
    id: 25,
    img: imgLaptop1,
    title: "Laptop hp",
    des: "8 Ram ,256 ssd",
    price: 1000,
    discount: true,
    discountPrice: 900,
    stars: 4,
  },
  {
    id: 26,
    img: imgHeadphone1,
    title: "HeadPhone",
    des: "hight edtions 2025 ",
    price: 250,
    discount: true,
    discountPrice: 190,
    stars: 4.5,
  },
  {
    id: 27,
    img: imgHeadphone2,
    title: "HeadPhone",
    des: "hight edtions 2025 ",
    price: 120,
    discount: true,
    discountPrice: 100,
    stars: 4.5,
  },
  {
    id: 28,
    img: imgLaptop2,
    title: "Laptop",
    des: "8 Ram , 256 ssd",
    price: 1799,
    discount: true,
    discountPrice: 1710,
    stars: 3.8,
  },
  {
    id: 29,
    img: imgCamera,
    title: "Camera",
    des: "type cannon ,200 mpx ",
    price: 699,
    discount: true,
    discountPrice: 600,
    stars: 4.7,
  },
  {
    id: 30,
    img: imgLaptop4,
    title: "Laptop",
    des: "8 Ram , 256 ssd",
    price: 1799,
    discount: true,
    discountPrice: 600,
    stars: 3.8,
  },
  {
    id: 31,
    img: imgLaptop2,
    title: "Laptop hp",
    des: "8 Ram ,256 ssd",
    price: 1000,
    stars: 4,
  },
  {
    id: 32,
    img: imgHeadphone2,
    title: "HeadPhone",
    des: "hight edtions 2025 ",
    price: 120,
    stars: 4.5,
  },
  {
    id: 33,
    img: imgIpod,
    title: "Ipad",
    des: "8 Ram ,256 , ios 18",
    price: 1199,
    stars: 3.8,
  },
  {
    id: 34,
    img: imgPhone,
    title: "Phone",
    des: "6 Ram ,128 ssd",
    price: 700,
    stars: 4,
  },
  {
    id: 35,
    img: imgHeadphone1,
    title: "HeadPhone",
    des: "hight edtions 2025 ",
    price: 250,
    stars: 4.5,
  },
  {
    id: 36,
    img: imgLaptop4,
    title: "Laptop",
    des: "8 Ram , 256 ssd",
    price: 1799,
    stars: 3.8,
  },
  {
    id: 37,
    img: imgIpod,
    title: "Ipad",
    des: "8 Ram ,256 , ios 18",
    price: 1199,
    stars: 3.8,
  },
  {
    id: 38,
    img: imgLaptop3,
    title: "Laptop",
    des: "8 Ram , 256 ssd",
    price: 1799,
    stars: 3.8,
  },
  {
    id: 39,
    img: imgCamera,
    title: "Camera",
    des: "type cannon ,200 mpx ",
    price: 699,
    stars: 4.7,
  },
  {
    id: 40,
    img: imgLaptop1,
    title: "Laptop hp",
    des: "8 Ram ,256 ssd",
    price: 1000,
    stars: 4,
  },
  {
    id: 41,
    img: imgHeadphone1,
    title: "HeadPhone",
    des: "hight edtions 2025 ",
    price: 250,
    stars: 4.5,
  },
  {
    id: 42,
    img: imgHeadphone2,
    title: "HeadPhone",
    des: "hight edtions 2025 ",
    price: 120,
    stars: 4.5,
  },
  {
    id: 43,
    img: imgLaptop2,
    title: "Laptop",
    des: "8 Ram , 256 ssd",
    price: 1799,
    stars: 3.8,
  },
  {
    id: 44,
    img: imgCamera,
    title: "Camera",
    des: "type cannon ,200 mpx ",
    price: 699,
    stars: 4.7,
  },
  {
    id: 45,
    img: imgLaptop4,
    title: "Laptop",
    des: "8 Ram , 256 ssd",
    price: 1799,
    stars: 3.8,
  },
  {
    id: 46,
    img: imgLaptop2,
    title: "Laptop hp",
    des: "8 Ram ,256 ssd",
    price: 1000,
    discount: true,
    discountPrice: 950,
    stars: 4,
  },
  {
    id: 47,
    img: imgHeadphone2,
    title: "HeadPhone",
    des: "hight edtions 2025 ",
    price: 120,
    discount: true,
    discountPrice: 100,
    stars: 4.5,
  },
  {
    id: 48,
    img: imgIpod,
    title: "Ipad",
    des: "8 Ram ,256 , ios 18",
    price: 1199,
    discount: true,
    discountPrice: 1099,
    stars: 3.8,
  },
  {
    id: 49,
    img: imgPhone,
    title: "Phone",
    des: "6 Ram ,128 ssd",
    price: 700,
    discount: true,
    discountPrice: 610,
    stars: 4,
  },
  {
    id: 50,
    img: imgHeadphone1,
    title: "HeadPhone",
    des: "hight edtions 2025 ",
    price: 250,
    discount: false,
    discountPrice: 90,
    stars: 4.5,
  },
  {
    id: 51,
    img: imgLaptop4,
    title: "Laptop",
    des: "8 Ram , 256 ssd",
    price: 1799,
    discount: false,
    discountPrice: 1600,
    stars: 3.8,
  },
  {
    id: 52,
    img: imgIpod,
    title: "Ipad",
    des: "8 Ram ,256 , ios 18",
    price: 1199,
    discount: true,
    discountPrice: 1099,
    stars: 3.8,
  },
  {
    id: 53,
    img: imgLaptop3,
    title: "Laptop",
    des: "8 Ram , 256 ssd",
    price: 1799,
    discount: true,
    discountPrice: 1600,
    stars: 3.8,
  },
  {
    id: 54,
    img: imgCamera,
    title: "Camera",
    des: "type cannon ,200 mpx ",
    price: 699,
    discount: true,
    discountPrice: 571,
    stars: 4.7,
  },
  {
    id: 55,
    img: imgLaptop1,
    title: "Laptop hp",
    des: "8 Ram ,256 ssd",
    price: 1000,
    discount: true,
    discountPrice: 910,
    stars: 4,
  },
  {
    id: 56,
    img: imgHeadphone1,
    title: "HeadPhone",
    des: "hight edtions 2025 ",
    price: 250,
    discount: false,
    discountPrice: 190,
    stars: 4.5,
  },
  {
    id: 57,
    img: imgHeadphone2,
    title: "HeadPhone",
    des: "hight edtions 2025 ",
    price: 120,
    discount: true,
    discountPrice: 90,
    stars: 4.5,
  },
  {
    id: 58,
    img: imgLaptop2,
    title: "Laptop",
    des: "8 Ram , 256 ssd",
    price: 1799,
    discount: true,
    discountPrice: 1600,
    stars: 3.8,
  },
  {
    id: 59,
    img: imgCamera,
    title: "Camera",
    des: "type cannon ,200 mpx ",
    price: 699,
    discount: false,
    discountPrice: 570,
    stars: 4.7,
  },
  {
    id: 60,
    img: imgLaptop4,
    title: "Laptop",
    des: "8 Ram , 256 ssd",
    price: 1799,
    discount: true,
    discountPrice: 1680,
    stars: 3.8,
  },
  {
    id: 61,
    img: imgLaptop2,
    title: "Laptop hp",
    des: "8 Ram ,256 ssd",
    price: 1000,
    discount: false,
    discountPrice: 910,
    stars: 4,
  },
  {
    id: 62,
    img: imgHeadphone2,
    title: "HeadPhone",
    des: "hight edtions 2025 ",
    price: 120,
    discount: false,
    discountPrice: 90,
    stars: 4.5,
  },
  {
    id: 63,
    img: imgIpod,
    title: "Ipad",
    des: "8 Ram ,256 , ios 18",
    price: 1199,
    discount: true,
    discountPrice: 1081,
    stars: 3.8,
  },
  {
    id: 64,
    img: imgPhone,
    title: "Phone",
    des: "6 Ram ,128 ssd",
    price: 700,
    discount: true,
    discountPrice: 590,
    stars: 4,
  },
  {
    id: 65,
    img: imgHeadphone1,
    title: "HeadPhone",
    des: "hight edtions 2025 ",
    price: 250,
    discount: true,
    discountPrice: 190,
    stars: 4.5,
  },
  {
    id: 66,
    img: imgLaptop4,
    title: "Laptop",
    des: "8 Ram , 256 ssd",
    price: 1799,
    discount: true,
    discountPrice: 1790,
    stars: 3.8,
  },
  {
    id: 67,
    img: imgIpod,
    title: "Ipad",
    des: "8 Ram ,256 , ios 18",
    price: 1199,
    discount: true,
    discountPrice: 1099,
    stars: 3.8,
  },
  {
    id: 68,
    img: imgLaptop3,
    title: "Laptop",
    des: "8 Ram , 256 ssd",
    price: 1799,
    discount: true,
    discountPrice: 1570,
    stars: 3.8,
  },
  {
    id: 69,
    img: imgCamera,
    title: "Camera",
    des: "type cannon ,200 mpx ",
    price: 699,
    discount: true,
    discountPrice: 590,
    stars: 4.7,
  },
  {
    id: 70,
    img: imgLaptop1,
    title: "Laptop hp",
    des: "8 Ram ,256 ssd",
    price: 1000,
    discount: true,
    discountPrice: 900,
    stars: 4,
  },
  {
    id: 71,
    img: imgHeadphone1,
    title: "HeadPhone",
    des: "hight edtions 2025 ",
    price: 250,
    discount: true,
    discountPrice: 190,
    stars: 4.5,
  },
  {
    id: 72,
    img: imgHeadphone2,
    title: "HeadPhone",
    des: "hight edtions 2025 ",
    price: 120,
    discount: true,
    discountPrice: 100,
    stars: 4.5,
  },
  {
    id: 73,
    img: imgLaptop2,
    title: "Laptop",
    des: "8 Ram , 256 ssd",
    price: 1799,
    discount: true,
    discountPrice: 1710,
    stars: 3.8,
  },
  {
    id: 74,
    img: imgCamera,
    title: "Camera",
    des: "type cannon ,200 mpx ",
    price: 699,
    discount: true,
    discountPrice: 600,
    stars: 4.7,
  },
  {
    id: 75,
    img: imgLaptop4,
    title: "Laptop",
    des: "8 Ram , 256 ssd",
    price: 1799,
    discount: true,
    discountPrice: 600,
    stars: 3.8,
  },
];
